import 'dart:typed_data';

import 'package:ed25519_edwards/ed25519_edwards.dart' as ed;
import 'package:flutter_test/flutter_test.dart';

import 'package:conduit/src/core/identity.dart';

void main() {
  test('loads the 64-byte private key generated by ed25519_edwards', () {
    final pair = ed.generateKey();
    final identity = DeviceIdentity(
      deviceId: 'TEST-0001',
      name: 'Test device',
      platform: 'windows',
      privateKey: Uint8List.fromList(pair.privateKey.bytes),
      publicKey: Uint8List.fromList(pair.publicKey.bytes),
    );

    final restored = DeviceIdentity.fromJson(identity.toJson());
    final message = Uint8List.fromList(<int>[1, 2, 3, 4]);
    final signature = restored.sign(message);

    expect(restored.privateKey, orderedEquals(identity.privateKey));
    expect(restored.publicKey, orderedEquals(identity.publicKey));
    expect(restored.verify(message, signature, restored.publicKey), isTrue);
  });
}
